version: 2.1
jobs:
  single-tuple-ghc-8-2:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v1-root-{{ checksum "stack-ghc-8.2.yaml" }}
            - stack-v1-root-
      - restore_cache:
          keys:
            - stack-v1-single-tuple-{{ checksum "stack-ghc-8.2.yaml" }}-{{ checksum "single-tuple/package.yaml" }}
            - stack-v1-single-tuple-
      - run:
          command: stack --stack-yaml stack-ghc-8.2.yaml --no-terminal test single-tuple
      - save_cache:
          key: stack-v1-root-{{ checksum "stack-ghc-8.2.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - save_cache:
          key: stack-v1-single-tuple-{{ checksum "stack-ghc-8.2.yaml" }}-{{ checksum "single-tuple/package.yaml" }}
          paths:
            - "single-tuple/.stack-work"
  single-tuple-ghc-8-4:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v1-root-{{ checksum "stack-ghc-8.4.yaml" }}
            - stack-v1-root-
      - restore_cache:
          keys:
            - stack-v1-single-tuple-{{ checksum "stack-ghc-8.4.yaml" }}-{{ checksum "single-tuple/package.yaml" }}
            - stack-v1-single-tuple-
      - run:
          command: stack --stack-yaml stack-ghc-8.4.yaml --no-terminal test single-tuple
      - save_cache:
          key: stack-v1-root-{{ checksum "stack-ghc-8.4.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - save_cache:
          key: stack-v1-single-tuple-{{ checksum "stack-ghc-8.4.yaml" }}-{{ checksum "single-tuple/package.yaml" }}
          paths:
            - "single-tuple/.stack-work"
  single-tuple-ghc-8-6:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v1-root-{{ checksum "stack-ghc-8.6.yaml" }}
            - stack-v1-root-
      - restore_cache:
          keys:
            - stack-v1-single-tuple-{{ checksum "stack-ghc-8.6.yaml" }}-{{ checksum "single-tuple/package.yaml" }}
            - stack-v1-single-tuple-
      - run:
          command: stack --stack-yaml stack-ghc-8.6.yaml --no-terminal test single-tuple
      - save_cache:
          key: stack-v1-root-{{ checksum "stack-ghc-8.6.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - save_cache:
          key: stack-v1-single-tuple-{{ checksum "stack-ghc-8.6.yaml" }}-{{ checksum "single-tuple/package.yaml" }}
          paths:
            - "single-tuple/.stack-work"
  list-tuple-ghc-8-2:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v1-root-{{ checksum "stack-ghc-8.2.yaml" }}
            - stack-v1-root-
      - restore_cache:
          keys:
            - stack-v1-list-tuple-{{ checksum "stack-ghc-8.2.yaml" }}-{{ checksum "list-tuple/package.yaml" }}
            - stack-v1-list-tuple-
      - run:
          command: stack --stack-yaml stack-ghc-8.2.yaml --no-terminal build list-tuple # test causes GHC panic :(
      - save_cache:
          key: stack-v1-root-{{ checksum "stack-ghc-8.2.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - save_cache:
          key: stack-v1-list-tuple-{{ checksum "stack-ghc-8.2.yaml" }}-{{ checksum "list-tuple/package.yaml" }}
          paths:
            - "list-tuple/.stack-work"
  list-tuple-ghc-8-4:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v1-root-{{ checksum "stack-ghc-8.4.yaml" }}
            - stack-v1-root-
      - restore_cache:
          keys:
            - stack-v1-list-tuple-{{ checksum "stack-ghc-8.4.yaml" }}-{{ checksum "list-tuple/package.yaml" }}
            - stack-v1-list-tuple-
      - run:
          command: stack --stack-yaml stack-ghc-8.4.yaml --no-terminal test list-tuple
      - save_cache:
          key: stack-v1-root-{{ checksum "stack-ghc-8.4.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - save_cache:
          key: stack-v1-list-tuple-{{ checksum "stack-ghc-8.4.yaml" }}-{{ checksum "list-tuple/package.yaml" }}
          paths:
            - "list-tuple/.stack-work"
  list-tuple-ghc-8-6:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v1-root-{{ checksum "stack-ghc-8.6.yaml" }}
            - stack-v1-root-
      - restore_cache:
          keys:
            - stack-v1-list-tuple-{{ checksum "stack-ghc-8.6.yaml" }}-{{ checksum "list-tuple/package.yaml" }}
            - stack-v1-list-tuple-
      - run:
          command: stack --stack-yaml stack-ghc-8.6.yaml --no-terminal test list-tuple
      - save_cache:
          key: stack-v1-root-{{ checksum "stack-ghc-8.6.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - save_cache:
          key: stack-v1-list-tuple-{{ checksum "stack-ghc-8.6.yaml" }}-{{ checksum "list-tuple/package.yaml" }}
          paths:
            - "list-tuple/.stack-work"
  homotuple-ghc-8-2:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v1-root-{{ checksum "stack-ghc-8.2.yaml" }}
            - stack-v1-root-
      - restore_cache:
          keys:
            - stack-v1-homotuple-{{ checksum "stack-ghc-8.2.yaml" }}-{{ checksum "homotuple/package.yaml" }}
            - stack-v1-homotuple-
      - run:
          command: stack --stack-yaml stack-ghc-8.2.yaml --no-terminal test homotuple
      - save_cache:
          key: stack-v1-root-{{ checksum "stack-ghc-8.2.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - save_cache:
          key: stack-v1-homotuple-{{ checksum "stack-ghc-8.2.yaml" }}-{{ checksum "homotuple/package.yaml" }}
          paths:
            - "homotuple/.stack-work"
  homotuple-ghc-8-4:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v1-root-{{ checksum "stack-ghc-8.4.yaml" }}
            - stack-v1-root-
      - restore_cache:
          keys:
            - stack-v1-homotuple-{{ checksum "stack-ghc-8.4.yaml" }}-{{ checksum "homotuple/package.yaml" }}
            - stack-v1-homotuple-
      - run:
          command: stack --stack-yaml stack-ghc-8.4.yaml --no-terminal test homotuple
      - save_cache:
          key: stack-v1-root-{{ checksum "stack-ghc-8.4.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - save_cache:
          key: stack-v1-homotuple-{{ checksum "stack-ghc-8.4.yaml" }}-{{ checksum "homotuple/package.yaml" }}
          paths:
            - "homotuple/.stack-work"
  homotuple-ghc-8-6:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-v1-root-{{ checksum "stack-ghc-8.6.yaml" }}
            - stack-v1-root-
      - restore_cache:
          keys:
            - stack-v1-homotuple-{{ checksum "stack-ghc-8.6.yaml" }}-{{ checksum "homotuple/package.yaml" }}
            - stack-v1-homotuple-
      - run:
          command: stack --stack-yaml stack-ghc-8.6.yaml --no-terminal test homotuple
      - save_cache:
          key: stack-v1-root-{{ checksum "stack-ghc-8.6.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - save_cache:
          key: stack-v1-homotuple-{{ checksum "stack-ghc-8.6.yaml" }}-{{ checksum "homotuple/package.yaml" }}
          paths:
            - "homotuple/.stack-work"
workflows:
  version: 2
  workflow:
    jobs:
      - single-tuple-ghc-8-2
      - single-tuple-ghc-8-4
      - single-tuple-ghc-8-6
      - list-tuple-ghc-8-2
      - list-tuple-ghc-8-4
      - list-tuple-ghc-8-6
      - homotuple-ghc-8-2
      - homotuple-ghc-8-4
      - homotuple-ghc-8-6
