name: homotuple
version: 0.1.0.0
github: "kakkun61/homotuple"
license: Apache
author: "Kazuki Okamoto"
maintainer: "kazuki.okamoto@kakkun61.com"
copyright: "2019 Kazuki Okamoto"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Homotuple, all whose elements are the same type
category: Data

description: Homotuple, all whose elements are the same type

dependencies:
- base >= 4.10 && < 4.13

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wmonomorphism-restriction
- -Wmissing-exported-signatures
- -Wmissing-home-modules
- -Wmissing-import-lists
- -Widentities
- -Wredundant-constraints
- -Wno-name-shadowing

when:
- condition: impl(ghc >= 8.4.0)
  ghc-options:
  - -Wmissing-export-lists
  - -Wpartial-fields

when:
- condition: impl(ghc >= 8.6.0)
  default-extensions:
  - NoStarIsType

library:
  source-dirs: src
  dependencies:
  - OneTuple >= 0.2 && < 0.3
  - Only >= 0.1 && < 0.2
  - single-tuple >= 0.1 && < 0.2
