name: homotuple
version: 0.1.0.0
github: "kakkun61/homotuple"
license: AllRightsReserved
author: "Kazuki Okamoto"
maintainer: "kazuki.okamoto@kakkun61.com"
copyright: "2019 Kazuki Okamoto"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Homotuple, all whose elements are the same type
category: Data


description: Please see the README on GitHub at <https://github.com/kakkun61/homotuple#readme>

dependencies:
- base

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wmonomorphism-restriction
- -Wmissing-exported-signatures
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wmissing-import-lists
- -Widentities
- -Wredundant-constraints
- -Wpartial-fields
- -Wno-name-shadowing

when:
- condition: impl(ghc >= 8.6.1)
  default-extensions:
  - NoStarIsType

library:
  source-dirs: src
  dependencies:
  - OneTuple
  - Only
  - single-tuple
