name: list-tuple
version: 0.1.1.0
github: "kakkun61/tuple"
license: Apache-2.0
author: "Kazuki Okamoto"
maintainer: "kazuki.okamoto@kakkun61.com"
copyright: "2019 Kazuki Okamoto"

extra-source-files:
- README.md
- ChangeLog.md
- template/*.hs

synopsis: List-like operations for tuples
category: Data

description: List-like operations for tuples

dependencies:
- base >= 4.10 && < 4.13

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wmonomorphism-restriction
- -Wmissing-exported-signatures
- -Wmissing-home-modules
- -Wmissing-import-lists
- -Widentities
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wno-unticked-promoted-constructors

when:
- condition: impl(ghc >= 8.4.0)
  ghc-options:
  - -Wmissing-export-lists
  - -Wpartial-fields

library:
  source-dirs: src
  dependencies:
  - single-tuple >= 0.1 && < 0.2
  - OneTuple >= 0.2 && < 0.3
  - Only >= 0.1 && < 0.2

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-import-lists
    dependencies:
    - list-tuple
    - hspec
    - should-not-typecheck
    - deepseq
    - text
    - Only
    - single-tuple
    when:
    - condition: impl(ghc >= 8.4.0)
      ghc-options:
      - -Wno-missing-export-lists

custom-setup:
  dependencies:
  - base
  - Cabal
  - directory
