name: build

on: [push, pull_request]

jobs:
  run-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: '9.10'
      - run: make run-template
      - run: |
          git ls-files --modified | tee modified-files.txt
          test -z "$(cat modified-files.txt)"

  build:
    needs: run-template
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.4.8', '9.8.4', '9.10.1']
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: |
          cabal update
          cabal v2-freeze
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            ./dist-newstyle
          key: cabal-${{ matrix.ghc }}-${{ hashFiles('/cabal.project.freeze') }}
          restore-keys: cabal-${{ matrix.ghc }}-
      - run: make build-only-dependencies
      - run: make

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.4.8', '9.8.4', '9.10.1']
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: |
          cabal update
          cabal v2-freeze
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            ./dist-newstyle
          key: cabal-${{ matrix.ghc }}-${{ hashFiles('/cabal.project.freeze') }}
          restore-keys: cabal-${{ matrix.ghc }}-
      - run: make test
